export const menuItems = [
  {
    id: "start-business",
    label: "Start your business",
    subItems: [
      {
        id: "subitem1",
        label: "Private Limited Company Registration",
        link: "private-limited-company-registration",
      },
      {
        id: "subitem2",
        label: "Public Limited Company Registration",
        link: "public-limited-company-registration",
      },
      {
        id: "subitem3",
        label: "One Person Company Registration",
        link: "one-person-company-registration",
      },
      {
        id: "subitem4",
        label: "Section 8 Company Registration",
        link: "section8-company-registration",
      },
      {
        id: "subitem5",
        label: "Limited Liability Partnership Firm Registration",
        link: "limited-liability-partnership-firm-registration",
      },
      {
        id: "subitem6",
        label: "Partnership Firm Registration",
        link: "partnership-firm-registration",
      },
      {
        id: "subitem7",
        label: "Society Registration",
        link: "society-registration",
      },
      {
        id: "subitem8",
        label: "Trust Registration",
        link: "trust-registration",
      },
    ],
  },
  {
    id: "tax-compliances",
    label: "Tax compliances",
    subItems: [
      {
        id: "subitem1",
        label: "GST",
        subSubItems: [
          "GST Registration ",
          "GST Returns Filing",
          "GST Refund",
          "GST Annual Return",
          "GST Notice Reply",
          "GST Audit",
          "GST Cancellation",
        ],
        links: [
          "gst-registration",
          "gst-returns-filing",
          "gst-refund",
          "gst-annual-return",
          "gst-notice-reply",
          "gst-audit",
          "gst-cancellation",
        ],
      },
      {
        id: "subitem2",
        label: "Income Tax",
        subSubItems: [
          "Income Tax Returns (ITR)",
          "Income Tax Notice Reply",
          "Income Tax Scrutiny",
          "Income Tax Appeal to CIT(A)",
          "Income Tax Appeal to ITAT",
          "Income Tax Audit",
          "TDS Return Filing",
        ],
        links: [
          "income-tax-returns",
          "income-tax-notice-reply",
          "income-tax-scrutiny",
          "income-tax-appeal-to-cit",
          "income-tax-appeal-to-itat",
          "income-tax-audit",
          "income-tax-filing",
        ],
      },
    ],
  },
  {
    id: "business-management",
    label: "Business Management",
    subItems: [
      {
        id: "subitem1",
        label: "Virtual CFO Solutions",
        link: "virtual-cfo-solutions",
      },
      {
        id: "subitem2",
        label: "Licenses & Registrations",
        subSubItems: [
          "Startup Registration",
          "MSME Registration",
          "IEC Code",
          "Trade License",
          "Digital Signature Certificate",
          "Provident Fund (PF) Registration",
          "ESI Registration",
          "Professional Tax Registration",
          "Shops and Establishments License",
          "Darpan Registration",
          "FCRA Registration",
          "Section 12A & 80G Registration",
        ],
        links: [
          "startup-registration",
          "msme-registration",
          "iec-code",
          "trade-license",
          "digital-signature-certificate",
          "provident-fund-registration",
          "esi-registration",
          "professional-tax-registration",
          "shops-establishments-license",
          "darpan-registration",
          "fcra-registration",
          "section-12a-80g-registration",
        ],
      },
      {
        id: "subitem3",
        label: "Company Compliances",
        subSubItems: [
          "Annual Company ROC Compliance ",
          "Company Audit",
          "Appointment of Director",
          "Resignation of Director",
          "Increase Authorized Capital",
          "Share Transfer of a Company",
          "Closure the Company",
          "Strike off Company",
          "Change in Object Clause",
          "Change in Address",
        ],
        links: [
          "annual-company-roc-compliance ",
          "company-audit",
          "appointment-of-director",
          "resignation-of-director",
          "increase-authorized-capital",
          "share-tansfer-of-a-Company",
          "closure-the-company",
          "strike-off-company",
          "change-in-object-clause",
          "change-in-address",
        ],
      },
      {
        id: "subitem4",
        label: "Partnership / LLP Compliances",
        subSubItems: [
          "Annual LLP ROC Compliance",
          "Partnership / LLP Audit",
          "Add Designated Partner",
          "Remove Designated Partner",
          "Changes to Partnership Agreement",
          "Dissolution of Partnership Firm",
          "Winding Up of LLP",
        ],
        links: [
          "annual-llp-roc-compliance",
          "partnership-or-llp-audit",
          "add-designated-partner",
          "remove-designated-partner",
          "changes-to-partnership-agreement",
          "dissolution-of-partnership-firm",
          "winding-up-of-llp",
        ],
      },
      {
        id: "subitem5",
        label: "Convert Your Business",
        subSubItems: [
          "Proprietorship to Partnership / LLP",
          "	Proprietorship to Company",
          "Partnership / LLP to Company",
          "Private to Public Company",
        ],
        links: [
          "proprietorship-to-patnership-llp",
          "proprietorship-to-company",
          "partnership-or-llp-company",
          "private-to-public-company",
        ],
      },
      {
        id: "subitem6",
        label: "Accounting Services",
        subSubItems: [
          "Accounting and Book-keeping",
          "Financial Due Diligence",
          "Payroll Services",
          "Retirement Planning",
        ],
        links: [
          "accounting-and-book-keeping",
          "financial-due-diligence",
          "payroll-services",
          "retirement-planning",
        ],
      },
    ],
  },

  {
    id: "valuation-services",
    label: "Valuation Services",
    subItems: [
      {
        id: "subitem1",
        label: "Business Valuation Services",
        links: "business-valuation-services",
      },
      {
        id: "subitem2",
        label: "Intangibles Valuation Services",
        links: "intangibles-valuation-services",
      },
      {
        id: "subitem3",
        label: "Valuation Under Companies Act",
        links: "valuation-under-companies-act",
      },
      {
        id: "subitem4",
        label: "Startup Valuation",
        links: "startup-valuation",
      },
      {
        id: "subitem5",
        label: "M & A Valuations",
        links: "m-and-a-valuations",
      },
    ],
  },
];
